name = "indo" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "indo.hesoyam.my.id"
custom_domain = true
[[routes]]
pattern = "shopee.co.id.indo.hesoyam.my.id"
custom_domain = true
[[routes]]
pattern = "cf.shopee.co.id.indo.hesoyam.my.id"
custom_domain = true
[[routes]]
pattern = "cv.shopee.sg.indo.hesoyam.my.id"
custom_domain = true
[[routes]]
pattern = "cvs-deo.shopeemobile.com.indo.hesoyam.my.id"
custom_domain = true
[[routes]]
pattern = "support.duolingo.com.indo.hesoyam.my.id"
custom_domain = true
[[routes]]
pattern = "englishtest-stage-7.duolingo.com.indo.hesoyam.my.id"
custom_domain = true
[[routes]]
pattern = "cdn.appsflyer.com.indo.hesoyam.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.indo.hesoyam.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.indo.hesoyam.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.indo.hesoyam.my.id"
custom_domain = true
[[routes]]
pattern = "classroom.google.com.indo.hesoyam.my.id"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "a0b344a8-fef4-49d7-b4c5-d6d8923e0b48"
